-- MySQL Script generated by MySQL Workbench
-- Thu Jul  9 10:48:59 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PGESTpizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PGESTpizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PGESTpizza` DEFAULT CHARACTER SET utf8 ;
USE `PGESTpizza` ;

-- -----------------------------------------------------
-- Table `PGESTpizza`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`client` (
  `id_client` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NOT NULL,
  `adresse` VARCHAR(80) NOT NULL,
  `email` VARCHAR(30) NULL,
  `tel` VARCHAR(10) NOT NULL,
  `point_fidelite` SMALLINT UNSIGNED NULL,
  `info` TEXT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`pizzaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`pizzaria` (
  `id_pizzaria` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` CHAR(7) NOT NULL,
  `adresse` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_pizzaria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`commande` (
  `id_commande` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `etat` VARCHAR(10) NOT NULL,
  `pizzaria_id_pizzaria` SMALLINT UNSIGNED NOT NULL,
  `client_id_client` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_commande`, `pizzaria_id_pizzaria`, `client_id_client`),
  INDEX `fk_commande_pizzaria1_idx` (`pizzaria_id_pizzaria` ASC) VISIBLE,
  INDEX `fk_commande_client1_idx` (`client_id_client` ASC) VISIBLE,
  CONSTRAINT `fk_commande_pizzaria1`
    FOREIGN KEY (`pizzaria_id_pizzaria`)
    REFERENCES `PGESTpizza`.`pizzaria` (`id_pizzaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_client1`
    FOREIGN KEY (`client_id_client`)
    REFERENCES `PGESTpizza`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`pizza` (
  `id_pizza` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `taille` CHAR(1) NOT NULL,
  `prix` TINYINT UNSIGNED NOT NULL,
  `pizzaria_id_pizzaria` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_pizza`, `pizzaria_id_pizzaria`),
  INDEX `fk_pizza_pizzaria1_idx` (`pizzaria_id_pizzaria` ASC) VISIBLE,
  CONSTRAINT `fk_pizza_pizzaria1`
    FOREIGN KEY (`pizzaria_id_pizzaria`)
    REFERENCES `PGESTpizza`.`pizzaria` (`id_pizzaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`produit` (
  `id_produit` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `produit` VARCHAR(20) NOT NULL,
  `quantite_un_gr_cl` SMALLINT UNSIGNED NOT NULL,
  `pizzaria_id_pizzaria` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_produit`, `pizzaria_id_pizzaria`),
  INDEX `fk_produit_pizzaria1_idx` (`pizzaria_id_pizzaria` ASC) VISIBLE,
  CONSTRAINT `fk_produit_pizzaria1`
    FOREIGN KEY (`pizzaria_id_pizzaria`)
    REFERENCES `PGESTpizza`.`pizzaria` (`id_pizzaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`employe` (
  `id_employe` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `statut` VARCHAR(15) NOT NULL,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NOT NULL,
  `adresse` VARCHAR(80) NOT NULL,
  `email` VARCHAR(30) NULL,
  `tel` VARCHAR(10) NOT NULL,
  `info` TEXT NULL,
  `pizzaria_id_pizzaria` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_employe`, `pizzaria_id_pizzaria`),
  INDEX `fk_employe_pizzaria1_idx` (`pizzaria_id_pizzaria` ASC) VISIBLE,
  CONSTRAINT `fk_employe_pizzaria1`
    FOREIGN KEY (`pizzaria_id_pizzaria`)
    REFERENCES `PGESTpizza`.`pizzaria` (`id_pizzaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`composition_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`composition_commande` (
  `pizza_id_pizza` TINYINT UNSIGNED NOT NULL,
  `commande_id_commande` MEDIUMINT UNSIGNED NOT NULL,
  `pizzaria_id_pizzaria` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`pizza_id_pizza`, `commande_id_commande`, `pizzaria_id_pizzaria`),
  INDEX `fk_composition_commande_pizza1_idx` (`pizza_id_pizza` ASC) VISIBLE,
  INDEX `fk_composition_commande_commande1_idx` (`commande_id_commande` ASC) VISIBLE,
  INDEX `fk_composition_commande_pizzaria1_idx` (`pizzaria_id_pizzaria` ASC) VISIBLE,
  CONSTRAINT `fk_composition_commande_pizza1`
    FOREIGN KEY (`pizza_id_pizza`)
    REFERENCES `PGESTpizza`.`pizza` (`id_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_composition_commande_commande1`
    FOREIGN KEY (`commande_id_commande`)
    REFERENCES `PGESTpizza`.`commande` (`id_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_composition_commande_pizzaria1`
    FOREIGN KEY (`pizzaria_id_pizzaria`)
    REFERENCES `PGESTpizza`.`pizzaria` (`id_pizzaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`recette` (
  `pizza_id_pizza` TINYINT UNSIGNED NOT NULL,
  `produit_id_produit` SMALLINT UNSIGNED NOT NULL,
  `pizzaria_id_pizzaria` SMALLINT UNSIGNED NOT NULL,
  PRIMARY KEY (`pizza_id_pizza`, `produit_id_produit`, `pizzaria_id_pizzaria`),
  INDEX `fk_Pizza_has_Ingredient_Pizza1_idx` (`pizza_id_pizza` ASC) VISIBLE,
  INDEX `fk_recette_produit1_idx` (`produit_id_produit` ASC) VISIBLE,
  INDEX `fk_recette_pizzaria1_idx` (`pizzaria_id_pizzaria` ASC) VISIBLE,
  CONSTRAINT `fk_Pizza_has_Ingredient_Pizza1`
    FOREIGN KEY (`pizza_id_pizza`)
    REFERENCES `PGESTpizza`.`pizza` (`id_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recette_produit1`
    FOREIGN KEY (`produit_id_produit`)
    REFERENCES `PGESTpizza`.`produit` (`id_produit`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recette_pizzaria1`
    FOREIGN KEY (`pizzaria_id_pizzaria`)
    REFERENCES `PGESTpizza`.`pizzaria` (`id_pizzaria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
