-- MySQL Script generated by MySQL Workbench
-- Fri Jul 24 19:40:25 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PGESTpizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PGESTpizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PGESTpizza` DEFAULT CHARACTER SET utf8 ;
USE `PGESTpizza` ;

-- -----------------------------------------------------
-- Table `PGESTpizza`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`client` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NOT NULL,
  `adresse` VARCHAR(80) NOT NULL,
  `email` VARCHAR(30) NULL,
  `tel` VARCHAR(10) NOT NULL,
  `point_fidelite` SMALLINT UNSIGNED NULL,
  `info` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`pizzaria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`pizzaria` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `adresse` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`statut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`statut` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`commande` (
  `id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `client_id` MEDIUMINT UNSIGNED NOT NULL,
  `Statut_id` INT UNSIGNED NOT NULL,
  `pizzaria_id` TINYINT UNSIGNED NOT NULL,
  `date` DATE NOT NULL,
  `prix` TINYINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_commande_pizzaria_idx` (`pizzaria_id` ASC) VISIBLE,
  INDEX `fk_commande_client_idx` (`client_id` ASC) VISIBLE,
  INDEX `fk_commande_Statut1_idx` (`Statut_id` ASC) VISIBLE,
  CONSTRAINT `fk_commande_pizzaria`
    FOREIGN KEY (`pizzaria_id`)
    REFERENCES `PGESTpizza`.`pizzaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `PGESTpizza`.`client` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_commande_Statut1`
    FOREIGN KEY (`Statut_id`)
    REFERENCES `PGESTpizza`.`statut` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`pizza` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `taille` CHAR(1) NOT NULL,
  `prix` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`produit` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`employe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`employe` (
  `id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NOT NULL,
  `adresse` VARCHAR(80) NOT NULL,
  `email` VARCHAR(30) NULL,
  `tel` VARCHAR(10) NOT NULL,
  `info` TEXT NULL,
  `pizzaria_id` TINYINT UNSIGNED NOT NULL,
  `Statut_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employe_pizzaria1_idx` (`pizzaria_id` ASC) VISIBLE,
  INDEX `fk_employe_Statut1_idx` (`Statut_id` ASC) VISIBLE,
  CONSTRAINT `fk_employe_pizzaria1`
    FOREIGN KEY (`pizzaria_id`)
    REFERENCES `PGESTpizza`.`pizzaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_employe_Statut1`
    FOREIGN KEY (`Statut_id`)
    REFERENCES `PGESTpizza`.`statut` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`composition_commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`composition_commande` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `commande_id` MEDIUMINT UNSIGNED NOT NULL,
  `pizza_id` TINYINT UNSIGNED NOT NULL,
  INDEX `fk_composition_commande_commande1_idx` (`commande_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_composition_commande_pizza`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `PGESTpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_composition_commande_commande`
    FOREIGN KEY (`commande_id`)
    REFERENCES `PGESTpizza`.`commande` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`recette`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`recette` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `pizza_id` TINYINT UNSIGNED NOT NULL,
  `produit_id` SMALLINT UNSIGNED NOT NULL,
  `quantite_un_gr_cl` TINYINT UNSIGNED NOT NULL,
  INDEX `fk_recette_produit1_idx` (`produit_id` ASC) VISIBLE,
  INDEX `fk_recette_pizza1_idx` (`pizza_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_recette_produit`
    FOREIGN KEY (`produit_id`)
    REFERENCES `PGESTpizza`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recette_pizza`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `PGESTpizza`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PGESTpizza`.`stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PGESTpizza`.`stock` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `produit_id` SMALLINT UNSIGNED NOT NULL,
  `pizzaria_id` TINYINT UNSIGNED NOT NULL,
  `quantite_un_gr_cl` SMALLINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stock_produit1_idx` (`produit_id` ASC) VISIBLE,
  INDEX `fk_Stock_pizzaria1_idx` (`pizzaria_id` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_produit1`
    FOREIGN KEY (`produit_id`)
    REFERENCES `PGESTpizza`.`produit` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stock_pizzaria1`
    FOREIGN KEY (`pizzaria_id`)
    REFERENCES `PGESTpizza`.`pizzaria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
